import type { Product } from "@/types/product"

// Define bench images that match the design with placeholders
const benchImages = {
  // First row - Casa benches and others
  casa: "https://www.woodard-furniture.com/media/catalog/product/cache/59ad28a0470972c014f7fb8dad2a2397/c/a/casa_3y0404.jpg",
  casaCushion: "https://www.woodard-furniture.com/media/catalog/product/cache/59ad28a0470972c014f7fb8dad2a2397/c/a/casa_3y0404st.jpg",
  newCentury: "https://www.woodard-furniture.com/media/catalog/product/cache/59ad28a0470972c014f7fb8dad2a2397/n/e/new_century_930004_woodard-furniture.jpg",
  colfax: "https://www.woodard-furniture.com/media/catalog/product/cache/59ad28a0470972c014f7fb8dad2a2397/C/o/Colfax-7K0404-92-woodard-furniture.jpg",
  delmar: "https://www.woodard-furniture.com/media/catalog/product/cache/59ad28a0470972c014f7fb8dad2a2397/D/e/Delmar_8C0004_2.jpg",

  // Second row
  tuoroArmless: "https://www.woodard-furniture.com/media/catalog/product/cache/59ad28a0470972c014f7fb8dad2a2397/W/o/Woodard_Tuoro_Armless_Bench_7S0423.jpg",
  tuoroArmlessCushion: "https://www.woodard-furniture.com/media/catalog/product/cache/59ad28a0470972c014f7fb8dad2a2397/t/u/tuoro-armless-bench-cushion-woodard.jpg",
  tuoroBackless: "https://www.woodard-furniture.com/media/catalog/product/cache/59ad28a0470972c014f7fb8dad2a2397/W/o/Woodard_Tuoro_Backless_Bench_7S0422.jpg",
  tuoroBacklessCushion: "https://www.woodard-furniture.com/media/catalog/product/cache/59ad28a0470972c014f7fb8dad2a2397/t/u/tuoro-piano-bench-cushion-woodard.jpg",
  tuoro: "https://www.woodard-furniture.com/media/catalog/product/cache/59ad28a0470972c014f7fb8dad2a2397/t/u/tuoro-bench-woodard.jpg",

  // Third row
  tuoroCushion: "https://www.woodard-furniture.com/media/catalog/product/cache/59ad28a0470972c014f7fb8dad2a2397/t/u/tuoro-bench-cushion-woodard.jpg",
  windsor: "https://www.woodard-furniture.com/media/catalog/product/cache/59ad28a0470972c014f7fb8dad2a2397/W/o/Woodard_Windsor_Bench_9S0414_1.jpg",
  windsorCushion: "https://www.woodard-furniture.com/media/catalog/product/cache/59ad28a0470972c014f7fb8dad2a2397/W/o/Woodard_Windsor_Bench_Cushion_9S0414_1.jpg",
  sheffield: "https://www.woodard-furniture.com/media/catalog/product/cache/59ad28a0470972c014f7fb8dad2a2397/s/h/sheffield_3c0004_bench.jpg",
  reunion: "https://www.woodard-furniture.com/media/catalog/product/cache/59ad28a0470972c014f7fb8dad2a2397/r/e/reunion_s648085-cal_woodard-outdoor-furniture.jpg",

  // Fourth row
  cortland: "https://www.woodard-furniture.com/media/catalog/product/cache/59ad28a0470972c014f7fb8dad2a2397/c/o/cortland_4z0494_crescent_bench.jpg",
  wiltshire: "https://www.woodard-furniture.com/media/catalog/product/cache/59ad28a0470972c014f7fb8dad2a2397/w/i/wiltshire_4q0414.jpg",
  gerie: "https://www.woodard-furniture.com/media/catalog/product/cache/59ad28a0470972c014f7fb8dad2a2397/C/a/Canaveral_S504085-CHG.jpg",
}

export function getProducts(): Product[] {
  return [
    {
      id: "1",
      name: "casa-bench",
      displayName: "Casa Bench",
      productCode: "3Y0404",
      image: benchImages.casa,
      price: 599,
      collection: "Casa",
      type: "Bench",
      material: "Wrought Iron",
      cushionType: "No Cushion",
      isStackable: false,
    },
    {
      id: "2",
      name: "casa-bench-with-optional-seat-cushion",
      displayName: "Casa Bench with Optional Seat Cushion",
      productCode: "3Y0404ST",
      image: benchImages.casaCushion,
      price: 699,
      collection: "Casa",
      type: "Bench",
      material: "Wrought Iron",
      cushionType: "Optional Seat Cushion",
      isStackable: false,
    },
    {
      id: "3",
      name: "new-century-bench-stackable",
      displayName: "New Century Bench - Stackable",
      productCode: "930004",
      image: benchImages.newCentury,
      price: 499,
      collection: "New Century",
      type: "Bench",
      material: "Aluminum",
      cushionType: "No Cushion",
      isStackable: true,
    },
    {
      id: "4",
      name: "colfax-bench",
      displayName: "Colfax Bench",
      productCode: "7K0404",
      image: benchImages.colfax,
      price: 649,
      collection: "Colfax",
      type: "Bench",
      material: "Aluminum",
      cushionType: "No Cushion",
      isStackable: false,
    },
    {
      id: "5",
      name: "delmar-stacking-bench",
      displayName: "Delmar Stacking Bench",
      productCode: "8C0004",
      image: benchImages.delmar,
      price: 549,
      collection: "Delmar",
      type: "Stacking Bench",
      material: "Aluminum",
      cushionType: "No Cushion",
      isStackable: true,
    },
    {
      id: "6",
      name: "tuoro-by-alexa-hampton-armless-bench",
      displayName: "Tuoro by Alexa Hampton Armless Bench",
      productCode: "7S0423",
      image: benchImages.tuoroArmless,
      price: 749,
      collection: "Tuoro",
      type: "Armless Bench",
      material: "Aluminum",
      cushionType: "No Cushion",
      isStackable: false,
    },
    {
      id: "7",
      name: "tuoro-by-alexa-hampton-armless-bench-with-optional-seat-cushion",
      displayName: "Tuoro by Alexa Hampton Armless Bench with Optional Seat Cushion",
      productCode: "7S0423ST",
      image: benchImages.tuoroArmlessCushion,
      price: 849,
      collection: "Tuoro",
      type: "Armless Bench",
      material: "Aluminum",
      cushionType: "Optional Seat Cushion",
      isStackable: false,
    },
    {
      id: "8",
      name: "tuoro-by-alexa-hampton-backless-bench",
      displayName: "Tuoro by Alexa Hampton Backless Bench",
      productCode: "7S0422",
      image: benchImages.tuoroBackless,
      price: 699,
      collection: "Tuoro",
      type: "Backless Bench",
      material: "Aluminum",
      cushionType: "No Cushion",
      isStackable: false,
    },
    {
      id: "9",
      name: "tuoro-by-alexa-hampton-backless-bench-with-optional-seat-cushion",
      displayName: "Tuoro by Alexa Hampton Backless Bench with Optional Seat Cushion",
      productCode: "7S0422ST",
      image: benchImages.tuoroBacklessCushion,
      price: 799,
      collection: "Tuoro",
      type: "Backless Bench",
      material: "Aluminum",
      cushionType: "Optional Seat Cushion",
      isStackable: false,
    },
    {
      id: "10",
      name: "tuoro-by-alexa-hampton-bench",
      displayName: "Tuoro by Alexa Hampton Bench",
      productCode: "7S0414",
      image: benchImages.tuoro,
      price: 799,
      collection: "Tuoro",
      type: "Bench",
      material: "Aluminum",
      cushionType: "No Cushion",
      isStackable: false,
    },
    {
      id: "11",
      name: "tuoro-by-alexa-hampton-bench-with-optional-seat-cushion",
      displayName: "Tuoro by Alexa Hampton Bench with Optional Seat Cushion",
      productCode: "7S0414ST",
      image: benchImages.tuoroCushion,
      price: 899,
      collection: "Tuoro",
      type: "Bench",
      material: "Aluminum",
      cushionType: "Optional Seat Cushion",
      isStackable: false,
    },
    {
      id: "12",
      name: "windsor-bench-stackable",
      displayName: "Windsor Bench - Stackable",
      productCode: "9S0414",
      image: benchImages.windsor,
      price: 599,
      collection: "Windsor",
      type: "Bench",
      material: "Aluminum",
      cushionType: "No Cushion",
      isStackable: true,
    },
    {
      id: "13",
      name: "windsor-bench-with-optional-seat-cushion",
      displayName: "Windsor Bench with Optional Seat Cushion",
      productCode: "9S0414ST",
      image: benchImages.windsorCushion,
      price: 699,
      collection: "Windsor",
      type: "Bench",
      material: "Aluminum",
      cushionType: "Optional Seat Cushion",
      isStackable: false,
    },
    {
      id: "14",
      name: "sheffield-bench",
      displayName: "Sheffield Bench",
      productCode: "3C0004",
      image: benchImages.sheffield,
      price: 649,
      collection: "Sheffield",
      type: "Bench",
      material: "Wrought Iron",
      cushionType: "No Cushion",
      isStackable: false,
    },
    {
      id: "15",
      name: "reunion-bench",
      displayName: "Reunion Bench",
      productCode: "S640B5",
      image: benchImages.reunion,
      price: 899,
      collection: "Reunion",
      type: "Bench",
      material: "Teak",
      cushionType: "No Cushion",
      isStackable: false,
    },
    {
      id: "16",
      name: "cortland-cushion-crescent-shaped-bench",
      displayName: "Cortland Cushion Crescent Shaped Bench",
      productCode: "4Z0494",
      image: benchImages.cortland,
      price: 1299,
      collection: "Cortland",
      type: "Bench",
      material: "Aluminum",
      cushionType: "Included Cushion",
      isStackable: false,
    },
    {
      id: "17",
      name: "wiltshire-bench-stackable",
      displayName: "Wiltshire Bench - Stackable",
      productCode: "4Q0414",
      image: benchImages.wiltshire,
      price: 649,
      collection: "Wiltshire",
      type: "Bench",
      material: "Wrought Iron",
      cushionType: "No Cushion",
      isStackable: true,
    },
    {
      id: "18",
      name: "gerie-curved-backless-bench-ottoman",
      displayName: "Gerie Curved Backless Bench/Ottoman",
      productCode: "S540B5",
      image: benchImages.gerie,
      price: 799,
      collection: "Gerie",
      type: "Backless Bench",
      material: "Wicker",
      cushionType: "Included Cushion",
      isStackable: false,
    },
  ]
}
